### ISSUE TITLE
bug: 502 error: gunicorn worker timeout when there are a lot of subtopics

### ISSUE THREAD

**Issue by dpriskorn** [dpriskorn/WikidataTopicCurator#31]
https://www.wikidata.org/wiki/Q11451 example
check how many subtopics?
how do we speed up the process?

**Comment by dpriskorn** [comment]
async and Wikibase REST API is the obvious solution.

**Comment by Ainali** [comment]
This one caused a 502: http://162.19.226.24:8080/check_subclass_of?qid=Q46952&lang=sv&subgraph=riksdagen_documents

**Comment by Ainali** [comment]
This one also: http://162.19.226.24:8080/check_subclass_of?qid=Q2990807&lang=sv&subgraph=riksdagen_documents

**Comment by dpriskorn** [comment]
I increased the gunicorn worker timeout to 200 seconds. It's not a good long term solution. The waiting is for getting labels and descriptions asynchronously from the Wikibase REST API.
This tool is currently hosted in Europe far from the WMF datacenter so it takes a while when there are many subtopics.

**Comment by dpriskorn** [comment]
Oh, I might be wrong. 
![image](https://github.com/dpriskorn/WikidataTopicCurator/assets/68460690/cbb4aafc-06a4-4334-85e0-48b3bea9242e)
This indicates the worker crashes because of a bug. I'll have to test this more to find the cause.
Alternatively just rewrite it using Javascript.

**Comment by dpriskorn** [comment]
Found a bug. Working on a fix.

**Comment by dpriskorn** [comment]
Cut off 7 seconds by disabling the fetch for totals
![image](https://github.com/dpriskorn/WikidataTopicCurator/assets/68460690/279278a8-1dc0-46dd-9a11-1626ff92486d)

**Comment by dpriskorn** [comment]
I deployed the fixes above. Timeout is now 120 seconds.

**Comment by dpriskorn** [comment]
Both reported 502s above now work. Please report further 502s :)

**Comment by dpriskorn** [comment]
Hard test for new QLever SPARQL implementation: http://localhost:5000/check_subclass_of?qid=Q156&lang=en&subgraph=scientific_articles with 62 subtopics.
Took 39s which is still far too long.
